---
Name: siteconfig_error_pages
After: 
    - "#cmsdefaultadmin"
---
SilverStripe\CMS\Controllers\CMSPageAddController:
    extensions:
        - WebbuildersGroup\SiteConfigErrorPages\Extensions\SiteConfigErrorPageCMSMain


SilverStripe\CMS\Controllers\CMSPageEditController:
    extensions:
        - WebbuildersGroup\SiteConfigErrorPages\Extensions\SiteConfigErrorPageCMSMain


SilverStripe\CMS\Controllers\CMSPageSettingsController:
    extensions:
        - WebbuildersGroup\SiteConfigErrorPages\Extensions\SiteConfigErrorPageCMSMain


SilverStripe\SiteConfig\SiteConfig:
    extensions:
        - WebbuildersGroup\SiteConfigErrorPages\Extensions\SiteConfigErrorPagesExtension

SilverStripe\CMS\Model\SiteTree:
    hide_from_cms_tree:
        - SilverStripe\ErrorPage\ErrorPage
